name: "Watch Activity"
description: "Watch user's activity."
inputs:
  stateId:
    description: "State Id to keep track on the Kernel side"
  eventName:
    description: "Event Name that triggered the run"
  eventPayload:
    description: "Event Payload for the plugin"
  settings:
    description: "Settings for the plugin"
  authToken:
    description: "Auth Token to auth as the Kernel"
  ref:
    description: "GitHub branch reference for the run"
  signature:
    description: "The kernel signature"
outputs:
  result:
    description: "Actions taken by the watcher."
    value: ${{ steps.main.outputs.result }}
runs:
  using: "composite"
  steps:
    - name: Setup Deno
      uses: denoland/setup-deno@v2
    - name: Run main script
      shell: bash
      run: deno run --unstable-sloppy-imports --allow-all --unstable-kv dist/index.js
