### POST request to run the plugin
POST http://localhost:3000
Content-Type: application/json

{
  "stateId": "some-state-id",
  "eventName": "issues.closed",
  "eventPayload": {
    "repository": {
      "owner": {
        "login": "ubiquity"
      }
    }
  },
  "settings": {
    "warning": "3.5 days",
    "watch": {
      "optOut": []
    },
    "disqualification": "7 days"
  },
  "authToken": "{{GITHUB_TOKEN}}",
  "ref": "development",
  "signature": "1234"
}