create table "public"."repositories" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "url" character varying not null,
    "last_check" timestamp with time zone not null default now(),
    "deadline" timestamp with time zone not null
);


alter table "public"."repositories" enable row level security;

CREATE UNIQUE INDEX repositories_pkey ON public.repositories USING btree (id);

CREATE UNIQUE INDEX repositories_url_key ON public.repositories USING btree (url);

alter table "public"."repositories" add constraint "repositories_pkey" PRIMARY KEY using index "repositories_pkey";

alter table "public"."repositories" add constraint "repositories_url_key" UNIQUE using index "repositories_url_key";

grant delete on table "public"."repositories" to "anon";

grant insert on table "public"."repositories" to "anon";

grant references on table "public"."repositories" to "anon";

grant select on table "public"."repositories" to "anon";

grant trigger on table "public"."repositories" to "anon";

grant truncate on table "public"."repositories" to "anon";

grant update on table "public"."repositories" to "anon";

grant delete on table "public"."repositories" to "authenticated";

grant insert on table "public"."repositories" to "authenticated";

grant references on table "public"."repositories" to "authenticated";

grant select on table "public"."repositories" to "authenticated";

grant trigger on table "public"."repositories" to "authenticated";

grant truncate on table "public"."repositories" to "authenticated";

grant update on table "public"."repositories" to "authenticated";

grant delete on table "public"."repositories" to "service_role";

grant insert on table "public"."repositories" to "service_role";

grant references on table "public"."repositories" to "service_role";

grant select on table "public"."repositories" to "service_role";

grant trigger on table "public"."repositories" to "service_role";

grant truncate on table "public"."repositories" to "service_role";

grant update on table "public"."repositories" to "service_role";


