create table "public"."issues" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "url" character varying not null,
    "last_reminder" timestamp with time zone default null,
    "last_check" timestamp with time zone not null default now(),
    "deadline" timestamp with time zone not null
);

alter table "public"."issues" enable row level security;

CREATE UNIQUE INDEX issues_pkey ON public.issues USING btree (id);

CREATE UNIQUE INDEX issues_url_key ON public.issues USING btree (url);

alter table "public"."issues" add constraint "issues_pkey" PRIMARY KEY using index "issues_pkey";

alter table "public"."issues" add constraint "issues_url_key" UNIQUE using index "issues_url_key";

grant delete on table "public"."issues" to "service_role";

grant insert on table "public"."issues" to "service_role";

grant references on table "public"."issues" to "service_role";

grant select on table "public"."issues" to "service_role";

grant trigger on table "public"."issues" to "service_role";

grant truncate on table "public"."issues" to "service_role";

grant update on table "public"."issues" to "service_role";


